### PR TITLE
YD-190 Make goals polymorphic

### PR DESCRIPTION
**Pull request by aristotelos**
Copying solution from Bert :)
Created common base class

### CODE REVIEW

**Comment by aristotelos** [comment]
I just updated Swagger for this too

**Comment by aristotelos** [comment]
Maybe it's an idea to have the swagger definition as a file in github too? Then the changes can be reviewed

**Comment by Bert-R** [comment]
> Maybe it's an idea to have the swagger definition as a file in github too? Then the changes can be reviewed

Yes, that's the plan, see [YD-177](http://jira.yona.nu/browse/YD-177). I expect to do that this Saturday.

**Comment by Bert-R** [comment]
> Maybe a more extensive explanation would be good here ;)
If time permits, I plan to write a [Gist`](https://help.github.com/articles/about-gists/) about our ``JsonRootRelProvider``. There I'll touch the polymorphic DTOs too, so that can act as a piece of documentation.

**Comment by Bert-R** [comment]
Clean solution!

**Pull request merged**
