### PR TITLE
YD-122 Refactored messages, added tests

### PR DESCRIPTION
**Pull request by aristotelos**
Fixed bug: BuddyConnectRequestMessage had status NOT_REQUESTED
Disclosing status on all messages (have to add some tests still for updating messages after action)

### CODE REVIEW

**Comment by Bert-R** [comment]
retest this please

(talking to Jenkins)

**Comment by yonabuild** [comment]
Can one of the admins verify this patch?

**Comment by yonabuild** [comment]
Add to whitelist

Groetjes, Bert

**Comment by Bert-R** [comment]
retest this please

(talking to Jenkins)

**Pull request merged**
