### PR TITLE
YD-141 move test specific assertion

### PR DESCRIPTION
**Pull request by Bert-R**
Is this what you meant? That's quite a bit less code than comment. Sorry for not calling you earlier.

### CODE REVIEW

**Comment by aristotelos** [comment]
This is what I meant. You can move `assertUserGetResponseDetailsWithPrivateDataCreatedOnBoddyRequest`, `assertUserWithPrivateDataCreatedOnBuddyRequest` to the `CreateUserOnBuddyRequestTest` class too.

**Comment by Bert-R** [comment]
These are used in by two tests: ``CreateUserOnBuddyRequestTest`` and ``BasicBuddyTest``

**Comment by Bert-R** [comment]
I did one more rename (to make it a test-case independent assertion): ``assertPrivateUserDataCreatedOnBuddyRequest`` into ``assertVpnProfile``. The other two cannot be moved into a test, as they are used in two tests.

**Comment by Bert-R** [comment]
I've renamed them to make the names test case independent, just expressing what they assert. Is this better?

**Comment by aristotelos** [comment]
Yes, a lot better! The "created on buddy request" logic is now only in the `CreateUserOnBuddyRequestTest`. and the "overwrite user" logic is now only in the `OverwriteUserTest`.

**Pull request merged**
