### PR TITLE
YD-87 finish unit test for AnalysisEngineService

### PR DESCRIPTION
**Pull request by aristotelos**
Merged master in work from Mikko.

### CODE REVIEW

**Comment by Bert-R** [comment]
This branch needs to be synced with the master.

**Comment by aristotelos** [comment]
Indeed, I will do that.

**Comment by aristotelos** [comment]
Done

**Comment by Bert-R** [comment]
This type of test seems to be a good value add. Let's make more of these. I'm going to merge this PR.

**Pull request merged**
