### PR TITLE
Add Jenkins pipeline stages for Beta

### PR DESCRIPTION
**Pull request by kti-richard**
As discussed (and late) here is the proposed Jenkinsfile changes to add the stages for prompting and deploying to beta.

### CODE REVIEW

**Comment by yonabuild** [comment]
Build triggered. sha1 is merged.

**Comment by yonabuild** [comment]
Build started sha1 is merged.

**Comment by yonabuild** [comment]
Build finished.

**Comment by kti-richard** [comment]
Related - The slave is not connecting - getting 403 Unauthorized.  Using the urls/proxy values from the build server slave, and have double checked the secrets match the values in slack.

**Pull request merged**
